### POST request to create-patent
POST http://localhost:4004/patients/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Kafka Test u2",
  "email": "kafka2u@gmail.com",
  "address": "123 Main St",
  "dateOfBirth": "1987-10-17T00:00",
  "registeredDate": "1987-10-17T00:00"

}


###